#!/usr/bin/env bash
# Installs nginx server with specified requirements
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/defaul
service nginx restart

# Create an index.html as default site
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
