#!/usr/bin/env bash
# Installs nginx on your web-01
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Configure your Nginx server so that /redirect_me is redirecting to another page
echo 'Hello World!' > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://stackoverflow.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
