#!/usr/bin/env bash
# Installs nginx on your web-01
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
service nginx start
