#!/usr/bin/env bash
# Installs nginx on your web-01
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Configure your Nginx server so that /redirect_me is redirecting to another page
echo 'Hello World!' > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://facebook.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

sudo ervice nginx restart
