#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command
#Displays Y U no love me?!
#Deletes the file /var/run/myscript.pid 

cleanup(){
    rm -f /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while [[ : ]]
do 
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && cleanup' SIGTERM
    trap 'cleanup' SIGQUIT
done
