#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
#Displays username, user id, Home directory path

filename='/etc/passwd'
while read -r passwd;
do
echo "$passwd" | awk -F ":" '{print $1 ":" $3 ":" $6}'
done < $filename
