#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 8 ];
         then
          echo "Hi"
            else
                echo "Best School"
                fi
                ((i++))
                 done
